function TarotArray() {
  return [
    {
      id: 0, 
      title: 'Card Back', 
      divMean: 'Should I hide the modal in this state?',
      link: 'none'
    },
    {id: 1, title: 'The Fool', divMean: 'This is some sample text for the Fool card, tbh there\'s probably going to be more than 1 paragraph.', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-fool.htm'},
    {id: 2, title: 'The Magician', divMean: 'This is some sample text for the Magician card, tbh there\'s probably going to be more than 1 paragraph.', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-magician.htm'},
    {id: 3, title: 'The High Priestess', divMean: 'This is some sample text', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-highpriestess.htm'},
    {id: 4, title: 'The Empress', divMean: 'This is some sample text for', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-empress.htm'},
    {id: 5, title: 'The Emperor', divMean: 'This is some sample text', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-emperor.htm'},
    {id: 6, title: 'The Hierophant', divMean: 'This is some sample text', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-hierophant.htm'},
    {id: 7, title: 'The Lovers', divMean: 'This is some sample text', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-lovers.htm'},
    {id: 8, title: 'The Chariot', divMean: 'This is some sample text', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-chariot.htm'},
    {id: 9, title: 'Strength', divMean: 'This is some sample text', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-strength.htm'},
    {id: 10, title: 'The Hermit', divMean: 'This is some sample text', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-hermit.htm'},
    {id: 11, title: 'Wheel of Fortune', divMean: 'This is some sample text', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-wheeloffortune.htm'},
    {id: 12, title: 'Justice', divMean: 'This is some sample text', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-justice.htm'},
    {id: 13, title: 'The Hanged Man', divMean: 'This is some sample text', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-hangedman.htm'},
    {id: 14, title: 'Death', divMean: 'This is some sample text', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-death.htm'},
    {id: 15, title: 'Temperance', divMean: 'This is some sample text', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-temperance.htm'},
    {id: 16, title: 'The Devil', divMean: 'This is some sample text', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-devil.htm'},
    {id: 17, title: 'The Tower', divMean: 'This is some sample text', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-tower.htm'},
    {id: 18, title: 'The Star', divMean: 'This is some sample text', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-star.htm'},
    {id: 19, title: 'The Moon', divMean: 'This is some sample text', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-moon.htm'},
    {id: 20, title: 'The Sun', divMean: 'This is some sample text', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-sun.htm'},
    {id: 21, title: 'Judgement', divMean: 'This is some sample text', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-judgement.htm'},
    {id: 22, title: 'The World', divMean: 'This is some sample text', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-world.htm'},
    {
      id: 23, 
      title: 'Ace of Staves', 
      divMean: 'Creation, invention, enterprise, the powers which result in these; principle, beginning, source; birth, family, origin, and in a sense the virility which is behind them; the starting point of enterprises; according to another account, money, fortune, inheritance.', 
      rvsMean: 'Fall, decadence, ruin, perdition, to perish also a certain clouded joy.',
      bkgInfo: 'Warrior of Light (Tarquin Merricke), Final Fantasy XIV',
      link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-wands.htm#1'
    },
    {id: 24, title: 'Two of Staves', divMean: 'This is some sample text for Staves (wands)', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-wands.htm#2'},
    {id: 25, title: 'Three of Staves', divMean: 'This is some sample text for Staves (wands)', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-wands.htm#3'},
    {id: 26, title: 'Four of Staves', divMean: 'This is some sample text for Staves (wands)', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-wands.htm#4'},
    {id: 27, title: 'Five of Staves', divMean: 'This is some sample text for Staves (wands)', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-wands.htm#5'},
    {id: 28, title: 'Six of Staves', divMean: 'This is some sample text for Staves (wands)', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-wands.htm#6'},
    {
      id: 29, 
      title: 'Seven of Staves', 
      divMean: 'It is a card of valour, for, on the surface, six are attacking one, who has, however, the vantage position. On the intellectual plane, it signifies discussion, wordy strife; in business — negotiations, war of trade, barter, competition. It is further a card of success, for the combatant is on the top and his enemies may be unable to reach him.', 
      rvsMean: 'Perplexity, embarrassments, anxiety. It is also a caution against indecision.',
      bkgInfo: 'Warrior of Light (Mike Hawke), Final Fantasy XIV',
      link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-wands.htm#7'
    },
    {id: 30, title: 'Eight of Staves', divMean: 'This is some sample text for Staves (wands)', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-wands.htm#8'},
    {id: 31, title: 'Nine of Staves', divMean: 'This is some sample text for Staves (wands)', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-wands.htm#9'},
    {id: 32, title: 'Ten of Staves', divMean: 'This is some sample text for Staves (wands)', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-wands.htm#10'},
    {id: 33, title: 'Page of Staves', divMean: 'This is some sample text for Staves (wands)', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-wands.htm#11'},
    {id: 34, title: 'Knight of Staves', divMean: 'This is some sample text for Staves (wands)', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-wands.htm#12'},
    {id: 35, title: 'Queen of Staves', divMean: 'This is some sample text for Staves (wands)', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-wands.htm#13'},
    {id: 36, title: 'King of Staves', divMean: 'This is some sample text for Staves (wands)', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-wands.htm#14'},
    {id: 37, title: 'Ace of Cups', divMean: 'This is some sample text for Cups', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-cups.htm#1'},
    {id: 38, title: 'Two of Cups', divMean: 'This is some sample text for Cups', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-cups.htm#2'},
    {id: 39, title: 'Three of Cups', divMean: 'This is some sample text for Cups', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-cups.htm#3'},
    {id: 40, title: 'Four of Cups', divMean: 'This is some sample text for Cups', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-cups.htm#4'},
    {id: 41, title: 'Five of Cups', divMean: 'This is some sample text for Cups', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-cups.htm#5'},
    {id: 42, title: 'Six of Cups', divMean: 'This is some sample text for Cups', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-cups.htm#6'},
    {id: 43, title: 'Seven of Cups', divMean: 'This is some sample text for Cups', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-cups.htm#7'},
    {id: 44, title: 'Eight of Cups', divMean: 'This is some sample text for Cups', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-cups.htm#8'},
    {id: 45, title: 'Nine of Cups', divMean: 'This is some sample text for Cups', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-cups.htm#9'},
    {id: 46, title: 'Ten of Cups', divMean: 'This is some sample text for Cups', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-cups.htm#10'},
    {id: 47, title: 'Page of Cups', divMean: 'This is some sample text for Cups', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-cups.htm#11'},
    {id: 48, title: 'Knight of Cups', divMean: 'This is some sample text for Cups', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-cups.htm#12'},
    {id: 49, title: 'Queen of Cups', divMean: 'This is some sample text for Cups', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-cups.htm#13'},
    {id: 50, title: 'King of Cups', divMean: 'This is some sample text for Cups', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-cups.htm#14'},
    {id: 51, title: 'Ace of Swords', divMean: 'This is some sample text for Swords', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-swords.htm#1'},
    {id: 52, title: 'Two of Swords', divMean: 'This is some sample text for Swords', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-swords.htm#2'},
    {id: 53, title: 'Three of Swords', divMean: 'This is some sample text for Swords', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-swords.htm#3'},
    {id: 54, title: 'Four of Swords', divMean: 'This is some sample text for Swords', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-swords.htm#4'},
    {id: 55, title: 'Five of Swords', divMean: 'This is some sample text for Swords', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-swords.htm#5'},
    {id: 56, title: 'Six of Swords', divMean: 'This is some sample text for Swords', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-swords.htm#6'},
    {id: 57, title: 'Seven of Swords', divMean: 'This is some sample text for Swords', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-swords.htm#7'},
    {id: 58, title: 'Eight of Swords', divMean: 'This is some sample text for Swords', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-swords.htm#8'},
    {id: 59, title: 'Nine of Swords', divMean: 'This is some sample text for Swords', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-swords.htm#9'},
    {id: 60, title: 'Ten of Swords', divMean: 'This is some sample text for Swords', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-swords.htm#10'},
    {id: 61, title: 'Page of Swords', divMean: 'This is some sample text for Swords', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-swords.htm#11'},
    {id: 62, title: 'Knight of Swords', divMean: 'This is some sample text for Swords', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-swords.htm#12'},
    {id: 63, title: 'Queen of Swords', divMean: 'This is some sample text for Swords', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-swords.htm#13'},
    {id: 64, title: 'King of Swords', divMean: 'This is some sample text for Swords', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-swords.htm#14'},
    {id: 65, title: 'Ace of Pentacles', divMean: 'This is some sample text for Pentacles', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-pentacles.htm#1'},
    {id: 66, title: 'Two of Pentacles', divMean: 'This is some sample text for Pentacles', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-pentacles.htm#2'},
    {id: 67, title: 'Three of Pentacles', divMean: 'This is some sample text for Pentacles', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-pentacles.htm#3'},
    {id: 68, title: 'Four of Pentacles', divMean: 'This is some sample text for Pentacles', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-pentacles.htm#4'},
    {id: 69, title: 'Five of Pentacles', divMean: 'This is some sample text for Pentacles', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-pentacles.htm#5'},
    {id: 70, title: 'Six of Pentacles', divMean: 'This is some sample text for Pentacles', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-pentacles.htm#6'},
    {id: 71, title: 'Seven of Pentacles', divMean: 'This is some sample text for Pentacles', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-pentacles.htm#7'},
    {id: 72, title: 'Eight of Pentacles', divMean: 'This is some sample text for Pentacles', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-pentacles.htm#8'},
    {id: 73, title: 'Nine of Pentacles', divMean: 'This is some sample text for Pentacles', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-pentacles.htm#9'},
    {id: 74, title: 'Ten of Pentacles', divMean: 'This is some sample text for Pentacles', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-pentacles.htm#10'},
    {id: 75, title: 'Page of Pentacles', divMean: 'This is some sample text for Pentacles', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-pentacles.htm#11'},
    {id: 76, title: 'Knight of Pentacles', divMean: 'This is some sample text for Pentacles', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-pentacles.htm#12'},
    {id: 77, title: 'Queen of Pentacles', divMean: 'This is some sample text for Pentacles', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-pentacles.htm#13'},
    {id: 78, title: 'King of Pentacles', divMean: 'This is some sample text for Pentacles', link: 'https://www.tarotcardmeanings.net/waite-tarot-comments/waite-on-tarot-pentacles.htm#14'},
    {id: undefined, title: 'Sad Mushroom', divMean: 'It appears there\'s an error here. Big sad.', link: ''},
  ];
}

export default TarotArray;