function TarotArray() {
  return [
    {id: 0, title: 'Card Back', content: 'Should I hide the modal in this state?'},
    {id: 1, title: 'The Fool', content: 'This is some sample text for the Fool card, tbh there\'s probably going to be more than 1 paragraph.', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-fool.htm'},
    {id: 2, title: 'The Magician', content: 'This is some sample text for the Magician card, tbh there\'s probably going to be more than 1 paragraph.', link: 'https://www.tarotcardmeanings.net/majorarcana/tarot-magician.htm'},
    {id: 3, title: 'The High Priestess', content: 'This is some sample text'},
    {id: 4, title: 'The Empress', content: 'This is some sample text for'},
    {id: 5, title: 'The Emperor', content: 'This is some sample text'},
    {id: 6, title: 'The Hierophant', content: 'This is some sample text'},
    {id: 7, title: 'The Lovers', content: 'This is some sample text'},
    {id: 8, title: 'The Chariot', content: 'This is some sample text'},
    {id: 9, title: 'Strength', content: 'This is some sample text'},
    {id: 10, title: 'The Hermit', content: 'This is some sample text'},
    {id: 11, title: 'Wheel of Fortune', content: 'This is some sample text'},
    {id: 12, title: 'Justice', content: 'This is some sample text'},
    {id: 13, title: 'The Hanged Man', content: 'This is some sample text'},
    {id: 14, title: 'Death', content: 'This is some sample text'},
    {id: 15, title: 'Temperance', content: 'This is some sample text'},
    {id: 16, title: 'The Devil', content: 'This is some sample text'},
    {id: 17, title: 'The Tower', content: 'This is some sample text'},
    {id: 18, title: 'The Star', content: 'This is some sample text'},
    {id: 19, title: 'The Moon', content: 'This is some sample text'},
    {id: 20, title: 'The Sun', content: 'This is some sample text'},
    {id: 21, title: 'Judgement', content: 'This is some sample text'},
    {id: 22, title: 'The World', content: 'This is some sample text'},
    {id: 23, title: 'Ace of Staves', content: 'This is some sample text for Staves (wands)'},
    {id: 24, title: 'Two of Staves', content: 'This is some sample text for Staves (wands)'},
    {id: 25, title: 'Three of Staves', content: 'This is some sample text for Staves (wands)'},
    {id: 26, title: 'Four of Staves', content: 'This is some sample text for Staves (wands)'},
    {id: 27, title: 'Five of Staves', content: 'This is some sample text for Staves (wands)'},
    {id: 28, title: 'Six of Staves', content: 'This is some sample text for Staves (wands)'},
    {id: 29, title: 'Seven of Staves', content: 'This is some sample text for Staves (wands)'},
    {id: 30, title: 'Eight of Staves', content: 'This is some sample text for Staves (wands)'},
    {id: 31, title: 'Nine of Staves', content: 'This is some sample text for Staves (wands)'},
    {id: 32, title: 'Ten of Staves', content: 'This is some sample text for Staves (wands)'},
    {id: 33, title: 'Page of Staves', content: 'This is some sample text for Staves (wands)'},
    {id: 34, title: 'Knight of Staves', content: 'This is some sample text for Staves (wands)'},
    {id: 35, title: 'Queen of Staves', content: 'This is some sample text for Staves (wands)'},
    {id: 36, title: 'King of Staves', content: 'This is some sample text for Staves (wands)'},
    {id: 37, title: 'Ace of Cups', content: 'This is some sample text for Cups'},
    {id: 38, title: 'Two of Cups', content: 'This is some sample text for Cups'},
    {id: 39, title: 'Three of Cups', content: 'This is some sample text for Cups'},
    {id: 40, title: 'Four of Cups', content: 'This is some sample text for Cups'},
    {id: 41, title: 'Five of Cups', content: 'This is some sample text for Cups'},
    {id: 42, title: 'Six of Cups', content: 'This is some sample text for Cups'},
    {id: 43, title: 'Seven of Cups', content: 'This is some sample text for Cups'},
    {id: 44, title: 'Eight of Cups', content: 'This is some sample text for Cups'},
    {id: 45, title: 'Nine of Cups', content: 'This is some sample text for Cups'},
    {id: 46, title: 'Ten of Cups', content: 'This is some sample text for Cups'},
    {id: 47, title: 'Page of Cups', content: 'This is some sample text for Cups'},
    {id: 48, title: 'Knight of Cups', content: 'This is some sample text for Cups'},
    {id: 49, title: 'Queen of Cups', content: 'This is some sample text for Cups'},
    {id: 50, title: 'King of Cups', content: 'This is some sample text for Cups'},
    {id: 51, title: 'Ace of Swords', content: 'This is some sample text for Swords'},
    {id: 52, title: 'Two of Swords', content: 'This is some sample text for Swords'},
    {id: 53, title: 'Three of Swords', content: 'This is some sample text for Swords'},
    {id: 54, title: 'Four of Swords', content: 'This is some sample text for Swords'},
    {id: 55, title: 'Five of Swords', content: 'This is some sample text for Swords'},
    {id: 56, title: 'Six of Swords', content: 'This is some sample text for Swords'},
    {id: 57, title: 'Seven of Swords', content: 'This is some sample text for Swords'},
    {id: 58, title: 'Eight of Swords', content: 'This is some sample text for Swords'},
    {id: 59, title: 'Nine of Swords', content: 'This is some sample text for Swords'},
    {id: 60, title: 'Ten of Swords', content: 'This is some sample text for Swords'},
    {id: 61, title: 'Page of Swords', content: 'This is some sample text for Swords'},
    {id: 62, title: 'Knight of Swords', content: 'This is some sample text for Swords'},
    {id: 63, title: 'Queen of Swords', content: 'This is some sample text for Swords'},
    {id: 64, title: 'King of Swords', content: 'This is some sample text for Swords'},
    {id: 65, title: 'Ace of Pentacles', content: 'This is some sample text for Pentacles'},
    {id: 66, title: 'Two of Pentacles', content: 'This is some sample text for Pentacles'},
    {id: 67, title: 'Three of Pentacles', content: 'This is some sample text for Pentacles'},
    {id: 68, title: 'Four of Pentacles', content: 'This is some sample text for Pentacles'},
    {id: 69, title: 'Five of Pentacles', content: 'This is some sample text for Pentacles'},
    {id: 70, title: 'Six of Pentacles', content: 'This is some sample text for Pentacles'},
    {id: 71, title: 'Seven of Pentacles', content: 'This is some sample text for Pentacles'},
    {id: 72, title: 'Eight of Pentacles', content: 'This is some sample text for Pentacles'},
    {id: 73, title: 'Nine of Pentacles', content: 'This is some sample text for Pentacles'},
    {id: 74, title: 'Ten of Pentacles', content: 'This is some sample text for Pentacles'},
    {id: 75, title: 'Page of Pentacles', content: 'This is some sample text for Pentacles'},
    {id: 76, title: 'Knight of Pentacles', content: 'This is some sample text for Pentacles'},
    {id: 77, title: 'Queen of Pentacles', content: 'This is some sample text for Pentacles'},
    {id: 78, title: 'King of Pentacles', content: 'This is some sample text for Pentacles'},
    {id: undefined, title: 'Mushroom', content: 'something is returning undefined'},
  ];
}

export default TarotArray;